### 로그인
POST http://{{host}}/api/v1/auth/login
Content-Type: application/json

{
  "email": {{test_user_email}},
  "password": {{test_user_password}}
}

### 유저 profile 수정
PUT http://{{host}}/api/v1/users/profile
Content-Type: application/json

{
  "companyName": "new company",
  "jobTitle": "new Job",
  "blogUrl": "newBlog.com",
  "careerLevel":  "ENTRY_LEVEL",
  "careerInterest": "BACKEND_DEVELOPER"
}
