services:
  db:
    image: mysql:8.0
    container_name: devtribe-feed-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devtribe-feed
      MYSQL_USER: sa
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: