version: '3.8'

services:
  controller:
    image: ngrinder/controller
    container_name: ngrinder-controller
    ports:
      - ${N_GRINDER_UI_PORT}:80
      - ${N_GRINDER_AGENT_PORT}:16001
    volumes:
      - ./scripts:/opt/ngrinder-controller/scripts
      - ngrinder_data:/opt/ngrinder-controller
    restart: always

  agent:
    image: ngrinder/agent
    container_name: ngrinder-agent
    depends_on:
      - controller
    environment:
      - CONTROLLER_IP=controller
    network_mode: "service:controller"
    restart: always

volumes:
  ngrinder_data: {}
