spring:
  application:
    name: devtribe-feed-api

  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      minimum-idle: ${HIKARI_MIN_IDLE}
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE}
      idle-timeout: ${HIKARI_IDLE_TIMEOUT}
      connection-timeout: ${HIKARI_CONNECTION_TIMEOUT}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    org.hibernate:
      type: error

management:
  server:
    port: ${MANAGEMENT_SERVER_PORT}

  metrics:
    enable:
      all: true
    distribution:
      percentiles:
        http.server.requests: 0.9, 0.95, 0.99
        jdbc.connections: 0.9, 0.95, 0.99
      percentiles-histogram:
        http.server.requests: true
        jdbc.connections: true


  endpoint:
    prometheus:
      access: read_only

  endpoints:
    web:
      exposure:
        include: prometheus, health, info, metrics

