global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "spring-boot-server"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:9200"]
    basic_auth:
      username: 'admin'
      password: 'secret'

  - job_name: 'mysqld_exporter'
    static_configs:
      - targets: [ 'host.docker.internal:9104' ]

  - job_name: 'node_exporter'
    static_configs:
      - targets: [ 'localhost:9100' ]