spring:
  elasticsearch:
    uris:
      - ${ES_URI_0}
    username: ${ES_USERNAME}
    password: ${ES_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  batch:
    jdbc:
      initialize-schema: always

server:
  port: ${SERVER_PORT}